/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SubCategoryRequest } from '../../models/sub-category-request';
import { SubCategoryResponse } from '../../models/sub-category-response';

export interface AddSubCategory$Params {
      body: SubCategoryRequest
}

export function addSubCategory(http: HttpClient, rootUrl: string, params: AddSubCategory$Params, context?: HttpContext): Observable<StrictHttpResponse<SubCategoryResponse>> {
  const rb = new RequestBuilder(rootUrl, addSubCategory.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SubCategoryResponse>;
    })
  );
}

addSubCategory.PATH = '/subCategories';
