/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SubCategoryResponse } from '../../models/sub-category-response';

export interface GetSubCategoryId$Params {
  id: number;
}

export function getSubCategoryId(http: HttpClient, rootUrl: string, params: GetSubCategoryId$Params, context?: HttpContext): Observable<StrictHttpResponse<SubCategoryResponse>> {
  const rb = new RequestBuilder(rootUrl, getSubCategoryId.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SubCategoryResponse>;
    })
  );
}

getSubCategoryId.PATH = '/subCategories/{id}';
