/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageSubCategoryResponse } from '../../models/page-sub-category-response';

export interface GetSubCategoryByCategoryId$Params {
  categoryId: number;
  page?: number;
  size?: number;
  name?: string;
  direction?: string;
}

export function getSubCategoryByCategoryId(http: HttpClient, rootUrl: string, params: GetSubCategoryByCategoryId$Params, context?: HttpContext): Observable<StrictHttpResponse<PageSubCategoryResponse>> {
  const rb = new RequestBuilder(rootUrl, getSubCategoryByCategoryId.PATH, 'get');
  if (params) {
    rb.query('categoryId', params.categoryId, {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
    rb.query('name', params.name, {});
    rb.query('direction', params.direction, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageSubCategoryResponse>;
    })
  );
}

getSubCategoryByCategoryId.PATH = '/subCategories/category';
