/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DigitalResponse } from '../../models/digital-response';

export interface GetDigitalPage$Params {
  userId: number;
}

export function getDigitalPage(http: HttpClient, rootUrl: string, params: GetDigitalPage$Params, context?: HttpContext): Observable<StrictHttpResponse<DigitalResponse>> {
  const rb = new RequestBuilder(rootUrl, getDigitalPage.PATH, 'get');
  if (params) {
    rb.path('userId', params.userId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DigitalResponse>;
    })
  );
}

getDigitalPage.PATH = '/bookBorrowed/digitalPage/{userId}';
