/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageBorrowedResponse } from '../../models/page-borrowed-response';

export interface GetBorrowedByUserId$Params {
  userId: number;
  page?: number;
  size?: number;
  sortBy?: string;
  direction?: string;
}

export function getBorrowedByUserId(http: HttpClient, rootUrl: string, params: GetBorrowedByUserId$Params, context?: HttpContext): Observable<StrictHttpResponse<PageBorrowedResponse>> {
  const rb = new RequestBuilder(rootUrl, getBorrowedByUserId.PATH, 'get');
  if (params) {
    rb.query('userId', params.userId, {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
    rb.query('sortBy', params.sortBy, {});
    rb.query('direction', params.direction, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageBorrowedResponse>;
    })
  );
}

getBorrowedByUserId.PATH = '/bookBorrowed/getByUserId';
