/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BorrowedResponse } from '../../models/borrowed-response';

export interface UpdateBookReturnIssueDate$Params {
  userId: number;
}

export function updateBookReturnIssueDate(http: HttpClient, rootUrl: string, params: UpdateBookReturnIssueDate$Params, context?: HttpContext): Observable<StrictHttpResponse<BorrowedResponse>> {
  const rb = new RequestBuilder(rootUrl, updateBookReturnIssueDate.PATH, 'put');
  if (params) {
    rb.path('userId', params.userId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BorrowedResponse>;
    })
  );
}

updateBookReturnIssueDate.PATH = '/bookBorrowed/{userId}';
