/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AnnouncementResponse {
  announcementId?: number;
  createdAt?: string;
  message?: string;
  read?: boolean;
  title?: string;
  type?: 'NEW_BOOK' | 'BOOK_DUE' | 'MEETING' | 'MILESTONE';
}
