/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AnnouncementRequest {
  message: string;
  title: string;
  type: 'NEW_BOOK' | 'BOOK_DUE' | 'MEETING' | 'MILESTONE';
}
