/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BookRequest {
  author: Array<string>;
  bookImageFile?: Blob;
  bookPdfFile?: Blob;
  detail?: string;
  isbn: string;
  name: string;
  publication: string;
  subCategoriesId: number;
}
