/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BookResponse {
  author?: Array<string>;
  averageRating?: number;
  bookId?: number;
  bookImagePath?: string;
  bookPdfPath?: string;
  bookStatus?: 'AVAILABLE' | 'BORROWED' | 'LOST';
  detail?: string;
  isbn?: string;
  name?: string;
  publication?: string;
  subCategoryId?: number;
}
