/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BorrowedResponse {
  bookId?: number;
  borrowedDate?: string;
  borrowedId?: number;
  remainingReturnDate?: string;
  returnedDate?: string;
  status?: 'BORROWED' | 'RETURNED' | 'OVERDUE' | 'DATE_EXTENDED';
  userId?: number;
}
