/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PageableObject } from '../models/pageable-object';
import { RatingFeedBackResponse } from '../models/rating-feed-back-response';
import { SortObject } from '../models/sort-object';
export interface PageRatingFeedBackResponse {
  content?: Array<RatingFeedBackResponse>;
  empty?: boolean;
  first?: boolean;
  last?: boolean;
  number?: number;
  numberOfElements?: number;
  pageable?: PageableObject;
  size?: number;
  sort?: SortObject;
  totalElements?: number;
  totalPages?: number;
}
