/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RatingUpperDetailsResponse {
  avgRating?: number;
  rating_1?: number;
  rating_2?: number;
  rating_3?: number;
  rating_4?: number;
  rating_5?: number;
  totalReviewNo?: number;
}
