/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RatingFeedbackDetailResponse {
  active?: boolean;
  comment?: Array<string>;
  id?: number;
  rating?: number;
  updatedAt?: string;
  userId?: number;
}
