/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RatingFeedBackResponse {
  active?: boolean;
  bookId?: number;
  comment?: Array<string>;
  createdAt?: string;
  id?: number;
  rating?: number;
  updatedAt?: string;
  userId?: number;
}
