/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RecycleHubResponse {
  co2Save?: number;
  energySaved?: number;
  growthRate?: number;
  paperSaved?: number;
  totalBook?: number;
  totalStudent?: number;
  waterSaved?: number;
}
