/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SubCategoryResponse {
  categoryId?: number;
  description?: string;
  name?: string;
  subCategoryId?: number;
}
