/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserRequest {
  email: string;
  name: string;
  password?: string;
  phoneNumber?: string;
  profileImg?: Blob;
  userRole?: Array<'STUDENT' | 'ADMIN' | 'TEACHER' | 'LIBRARIAN' | 'GUEST'>;
}
