/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserResponse {
  email?: string;
  name?: string;
  phoneNumber?: string;
  profileUrl?: string;
  userId?: number;
  userRole?: Array<'STUDENT' | 'ADMIN' | 'TEACHER' | 'LIBRARIAN' | 'GUEST'>;
}
