/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface DeleteFeedBack$Params {
  ratingId: number;
  userId: number;
  bookId: number;
}

export function deleteFeedBack(http: HttpClient, rootUrl: string, params: DeleteFeedBack$Params, context?: HttpContext): Observable<StrictHttpResponse<{
[key: string]: string;
}>> {
  const rb = new RequestBuilder(rootUrl, deleteFeedBack.PATH, 'delete');
  if (params) {
    rb.query('ratingId', params.ratingId, {});
    rb.query('userId', params.userId, {});
    rb.query('bookId', params.bookId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      [key: string]: string;
      }>;
    })
  );
}

deleteFeedBack.PATH = '/ratings';
