/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RatingFeedbackDetailResponse } from '../../models/rating-feedback-detail-response';

export interface GetAllRatingByBookId$Params {
  bookId: number;
  cursor?: number;
  limit?: number;
}

export function getAllRatingByBookId(http: HttpClient, rootUrl: string, params: GetAllRatingByBookId$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<RatingFeedbackDetailResponse>>> {
  const rb = new RequestBuilder(rootUrl, getAllRatingByBookId.PATH, 'get');
  if (params) {
    rb.query('bookId', params.bookId, {});
    rb.query('cursor', params.cursor, {});
    rb.query('limit', params.limit, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<RatingFeedbackDetailResponse>>;
    })
  );
}

getAllRatingByBookId.PATH = '/ratings/getAllByBookId';
