/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RatingUpperDetailsResponse } from '../../models/rating-upper-details-response';

export interface GetDetailsUpperRating$Params {
  bookId: number;
}

export function getDetailsUpperRating(http: HttpClient, rootUrl: string, params: GetDetailsUpperRating$Params, context?: HttpContext): Observable<StrictHttpResponse<RatingUpperDetailsResponse>> {
  const rb = new RequestBuilder(rootUrl, getDetailsUpperRating.PATH, 'get');
  if (params) {
    rb.query('bookId', params.bookId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RatingUpperDetailsResponse>;
    })
  );
}

getDetailsUpperRating.PATH = '/ratings/getUpperRating';
