/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RatingFeedBackResponse } from '../../models/rating-feed-back-response';
import { RatingRequest } from '../../models/rating-request';

export interface GiveBookRating$Params {
      body: RatingRequest
}

export function giveBookRating(http: HttpClient, rootUrl: string, params: GiveBookRating$Params, context?: HttpContext): Observable<StrictHttpResponse<RatingFeedBackResponse>> {
  const rb = new RequestBuilder(rootUrl, giveBookRating.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RatingFeedBackResponse>;
    })
  );
}

giveBookRating.PATH = '/ratings';
