/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AnnouncementRequest } from '../../models/announcement-request';
import { AnnouncementResponse } from '../../models/announcement-response';

export interface PostAnnouncement$Params {
      body: AnnouncementRequest
}

export function postAnnouncement(http: HttpClient, rootUrl: string, params: PostAnnouncement$Params, context?: HttpContext): Observable<StrictHttpResponse<AnnouncementResponse>> {
  const rb = new RequestBuilder(rootUrl, postAnnouncement.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AnnouncementResponse>;
    })
  );
}

postAnnouncement.PATH = '/notify';
