/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageUserResponse } from '../../models/page-user-response';

export interface GetUserByRole$Params {
  role: string;
  page?: number;
  size?: number;
  sortBy?: string;
  direction?: string;
}

export function getUserByRole(http: HttpClient, rootUrl: string, params: GetUserByRole$Params, context?: HttpContext): Observable<StrictHttpResponse<PageUserResponse>> {
  const rb = new RequestBuilder(rootUrl, getUserByRole.PATH, 'get');
  if (params) {
    rb.query('role', params.role, {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
    rb.query('sortBy', params.sortBy, {});
    rb.query('direction', params.direction, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageUserResponse>;
    })
  );
}

getUserByRole.PATH = '/user/role';
