/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ServerSentEventString } from '../../models/server-sent-event-string';

export interface ChatStream$Params {
  prompt: string;
}

export function chatStream(http: HttpClient, rootUrl: string, params: ChatStream$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ServerSentEventString>>> {
  const rb = new RequestBuilder(rootUrl, chatStream.PATH, 'get');
  if (params) {
    rb.query('prompt', params.prompt, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/event-stream', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ServerSentEventString>>;
    })
  );
}

chatStream.PATH = '/books/book-chat';
