/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface DownloadBookFile$Params {
  bookId: number;
  type: 'USER_IMAGE' | 'BOOK_IMAGE' | 'BOOK_PDF';
}

export function downloadBookFile(http: HttpClient, rootUrl: string, params: DownloadBookFile$Params, context?: HttpContext): Observable<StrictHttpResponse<Blob>> {
  const rb = new RequestBuilder(rootUrl, downloadBookFile.PATH, 'get');
  if (params) {
    rb.query('bookId', params.bookId, {});
    rb.query('type', params.type, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: 'application/octet-stream', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Blob>;
    })
  );
}

downloadBookFile.PATH = '/books/download';
