/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RecycleHubResponse } from '../../models/recycle-hub-response';

export interface GetAllRecycleHubDetails$Params {
}

export function getAllRecycleHubDetails(http: HttpClient, rootUrl: string, params?: GetAllRecycleHubDetails$Params, context?: HttpContext): Observable<StrictHttpResponse<RecycleHubResponse>> {
  const rb = new RequestBuilder(rootUrl, getAllRecycleHubDetails.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RecycleHubResponse>;
    })
  );
}

getAllRecycleHubDetails.PATH = '/books/getRecycle';
