/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface UploadBookImage$Params {
  bookId: number;
  type: 'USER_IMAGE' | 'BOOK_IMAGE' | 'BOOK_PDF';
      body?: FormData
}

export function uploadBookImage(http: HttpClient, rootUrl: string, params: UploadBookImage$Params, context?: HttpContext): Observable<StrictHttpResponse<{
[key: string]: string;
}>> {
  const rb = new RequestBuilder(rootUrl, uploadBookImage.PATH, 'post');
  if (params) {
    rb.query('bookId', params.bookId, {});
    rb.query('type', params.type, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      [key: string]: string;
      }>;
    })
  );
}

uploadBookImage.PATH = '/books/uploadImage';
